version: '3.8'
services:
  client-dev:
    build:
      context: .
      dockerfile: /client/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - /client/.env
  client-prod:
    build:
      context: .
      dockerfile: /client/Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - /client/.env.prod
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  server:
    build:
      context: .
      dockerfile: /server/Dockerfile
    container_name: sneaker-store-server
    environment:
      - PORT=3033
    ports:
      - '3033:3033'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
